export const GET_TASKS_BEGIN = "GET_TASKS_BEGIN";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_ERROR = "GET_TASKS_ERRORS";

export const CREATE_TASKS_BEGIN = "CREATE_TASKS_BEGIN";
export const CREATE_TASKS_SUCCESS = "CREATE_TASKS_SUCCESS";
export const CREATE_TASKS_ERROR = "CREATE_TASKS_ERROR";

export const UPDATE_TASKS_BEGIN = "UPDATE_TASKS_BEGIN";
export const UPDATE_TASKS_SUCCESS = "UPDATE_TASKS_SUCCESS";
export const UPDATE_TASKS_ERROR = "UPDATE_TASKS_ERROR";

export const DELETE_TASKS_BEGIN = "DELETE_TASKS_BEGIN";
export const DELETE_TASKS_SUCCESS = "DELETE_TASKS_SUCCESS";
export const DELETE_TASKS_ERROR = "DELETE_TASKS_ERROR";
